services:
  domotik-back:
    build: back
    depends_on:
      - mosquitto
    environment:
      TZ: 'Europe/Paris'
  domotik-front:
    build: front
    ports:
      - 3000:3000
    depends_on:
      - mosquitto
  domotik-datastore:
    build: datastore
    depends_on:
      - mosquitto
  mosquitto:
    image: 'jllopis/mosquitto:v1.4.14'
    ports:
      - 1883:1883
      - 9883:9883
