services:
  back:
    build: back
    depends_on:
      - mosquitto
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - .:/domotik
  front:
    build: front
    ports:
      - 3000:3000
    depends_on:
      - mosquitto
    volumes:
      - .:/database
  datastore:
    build: datastore
    depends_on:
      - mosquitto
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - .:/database
  mosquitto:
    build: mosquitto-image-with-websocket
    ports:
      - 1883:1883
      - 9883:9883
  grafana:
    build: grafana
    ports:
      - 3333:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
    depends_on:
      - datastore
    volumes:
      - .:/database
