services:
  domotik-back:
    build: back
    depends_on:
      - mosquitto
    environment:
      TZ: "Europe/Paris"
    command: mosquitto
  domotik-front:
    build: front
    ports:
      - 3000:3000
    depends_on:
      - mosquitto
      - influxdb
  domotik-bridge-to-influxdb:
    build: bridge-to-influxdb
    depends_on:
      - mosquitto
      - influxdb
  mosquitto:
    image: "jllopis/mosquitto:v1.4.14"
    ports:
      - 1883:1883
      - 9883:9883
  influxdb:
    image: "influxdb:alpine"
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: "domotik"