{
 "title": "trimestre",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "température journalière",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "température extérieure",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"value\") FROM \"sensors\" WHERE (\"name\" = 'esp12e') AND $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "esp12e" }
     ]
    },
    {
     "alias": "température intérieure",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT median(\"value\") FROM \"sensors\" WHERE (\"name\" = 'esp12e') AND $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "esp8266" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "esp32" }
     ]
    }
   ]
  },
  {
   "title": "Consommation électrique journalière",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "sumPerDay",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "daily_power_consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "sum(meanPerHour)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "meanPerHour" }
     ]
    }
   ]
  },
  {
   "title": "Consommation électrique horaire",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "max.",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "meanPerHour" }
     ]
    },
    {
     "alias": "min.",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "meanPerHour" }
     ]
    },
    {
     "alias": "moyenne",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "measures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "meanPerHour" }
     ]
    }
   ]
  }
 ]
}