name: create docker tasmota-converter
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  create-tasmota-converter:
    name: create docker Tasmota converter
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:tasmota-converter'
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/sylvek/tasmota-converter:latest
