name: create docker mosquitto
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  create-docker-mosquitto:
    name: create docker mosquitto 1.5 with websocket support
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:mosquitto-image-with-websocket'
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/sylvek/mosquitto:latest
